// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoAPI.DAL;

namespace ToDoDAL.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20211116154958_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToDoAPI.Core.Models.Label", b =>
                {
                    b.Property<int>("LabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("ItemOwner")
                        .HasColumnType("int");

                    b.Property<int>("ToDoListID")
                        .HasColumnType("int");

                    b.HasKey("LabelId");

                    b.HasIndex("ItemOwner");

                    b.ToTable("Labels");

                    b.HasData(
                        new
                        {
                            LabelId = 401,
                            Description = "Label1",
                            ItemOwner = 301,
                            ToDoListID = 201
                        });
                });

            modelBuilder.Entity("ToDoAPI.Core.Models.ToDoItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("TaskOwner")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ItemId");

                    b.HasIndex("TaskOwner");

                    b.ToTable("ToDoItems");

                    b.HasData(
                        new
                        {
                            ItemId = 301,
                            CreatedDate = new DateTime(2021, 11, 16, 15, 49, 58, 359, DateTimeKind.Utc).AddTicks(9309),
                            Description = "Item1",
                            TaskOwner = 201
                        });
                });

            modelBuilder.Entity("ToDoAPI.Core.Models.ToDoList", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Owner")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ListId");

                    b.HasIndex("Owner");

                    b.ToTable("ToDoLists");

                    b.HasData(
                        new
                        {
                            ListId = 201,
                            CreatedDate = new DateTime(2021, 11, 16, 15, 49, 58, 359, DateTimeKind.Utc).AddTicks(8472),
                            Description = "ListItem1",
                            Owner = 101
                        });
                });

            modelBuilder.Entity("ToDoAPI.Core.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 101,
                            Password = "Pa$$w0rd",
                            UserName = "Admin"
                        },
                        new
                        {
                            UserId = 102,
                            Password = "Pa$$w0rd",
                            UserName = "Standard"
                        });
                });

            modelBuilder.Entity("ToDoAPI.Core.Models.Label", b =>
                {
                    b.HasOne("ToDoAPI.Core.Models.ToDoItem", "ToDoItem")
                        .WithMany()
                        .HasForeignKey("ItemOwner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToDoAPI.Core.Models.ToDoItem", b =>
                {
                    b.HasOne("ToDoAPI.Core.Models.ToDoList", "ToDoList")
                        .WithMany()
                        .HasForeignKey("TaskOwner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToDoAPI.Core.Models.ToDoList", b =>
                {
                    b.HasOne("ToDoAPI.Core.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("Owner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
